name: build-test-deploy

on: push

jobs:
  build:
    runs-on: ubunta-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - run: npm install
      - run: npm run build

  test:
    needs: build
    runs-on: ubunta-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: use node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      - run: npm install
      - run: npm run build
  deploy:
    needs: test

    permission:
      contents: write
      pages: write
      id-token: write
    environment:
      name: production

permissions:
  contents: write
  pages: write
  id-token: write

environment:
  name: production
  url: ${{ steps.deployment.outputs.page_url }}

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: configure github pages
        uses: actions/configure-pages@v3

      - name: npm install
        run: npm install

      - name: npm run build
        run: npm run build

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v1

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v1
